name: Delete abandoned branches

on:
  # Run daily at midnight
  schedule:
    - cron: "0 0 * * *"
    - cron: "30 6 * * 1-5"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: Satisfy my repo CDO
    steps:
      - name: Delete those pesky dead branches
        uses: mn185177/github-actions-delete-abandoned-branches@master
        id: delete_stuff
        with:
          last_commit_age_days: 3
          ignore_branches: next-version,dont-deleteme

          # Disable dry run and actually get stuff deleted
          #dry_run: yes

      - name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete_stuff.outputs.deleted_branches }}'"
